@startuml "use-cases"
left to right direction
actor Coach as C
package MatchSquad {
usecase "Cadastro" as UC1
usecase "Consultar Agendamentos" as UC2
usecase "Confirmar Agendamentos" as UC3
usecase "Cancelar Agendamentos" as UC4
usecase "Ver Avaliações" as UC5
usecase "Estabelecer Tópicos da Reunião" as UC6
usecase "Ver Tópicos da Reunião" as UC7
usecase "Ver Perfil" as UC8
usecase "Editar Perfil" as UC9
}
C --> UC1
C --> UC2
C --> UC6
C --> UC7
C --> UC5
C --> UC8

(UC2)<..up..(UC3): <<extend>>
(UC2)<..up..(UC4): <<extend>>
(UC8)<..up..(UC9): <<extend>>

@enduml
