@startuml "Mentor use-cases"

left to right direction

actor Mentor as m
package MatchSquad-System{
usecase "Cadastro" as UC1
usecase "Cadastrar Mentoria" as UC2
usecase "Contatar plataforma" as UC3
usecase "Receber da plataforma" as UC4
usecase "Ver Perfil" as UC5
usecase "Editar Perfil" as UC6
usecase "Emitir relatorios" as UC7
usecase "Checar contratos" as UC8
usecase "Ver Avaliações" as UC9
usecase "Mentorar" as UC10
usecase "Confirmar Agendamento" as UC11
usecase "Cancelar agendamento" as UC12
usecase "Ver agendamentos" as UC13
}

m --> UC1
m --> UC2
m --> UC4
m --> UC3
m --> UC5
m --> UC7
m --> UC10
m --> UC13
m --> UC9

(UC12)..up..>(UC13) : <<extend>>
(UC11)..up..>(UC13) : <<extend>>
(UC6) .up.>(UC5) : <<includes>>

@enduml
