@startuml "Empreendedor use-cases"
left to right direction
actor Empreendedor as E
package MatchSquad {
usecase "Conhecer serviços" as UC1
usecase "Comprar plano" as UC2
usecase "Agendar Mentoria" as UC3
usecase "Pagar Mentoria" as UC4
usecase "Agendar Reunião com Coach" as UC5
usecase "Cancelar Agendamento" as UC6
usecase "Avaliar Reunião" as UC7
usecase "Trocar de Coach" as UC8
usecase "Consultar Agendamentos" as UC9
usecase "Escolher Coach" as UC10
usecase "Ver Informações sobre a Reunião" as UC11
}
E --> UC1
E --> UC2
E --> UC3
E --> UC5
E --> UC7
E --> UC9
E --> UC8
E --> UC10
E --> UC11

(UC3).up.>(UC4): <<include>>
(UC9)<..up..(UC6): <<extend>>

@enduml
