@startuml "Consultor use-cases"

left to right direction

actor Consultor as CO
package MatchSquad{
usecase "Consultar Agendamentos" as UC1
usecase "Confirmar Agendamento" as UC2
usecase "Cancelar Agendamento" as UC3
usecase "Editar Perfil" as UC4
usecase "Visualizar Histórico de Pagamentos" as UC5
usecase "Registrar Reunião" as UC6
usecase "Ver Avaliações" as UC9
usecase "Alterar Habilidades" as UC9
usecase "Alterar Preço Consultoria" as UC10
}

CO --> UC1
CO --> UC4
CO --> UC5


(UC2)<.up.(UC1) : <<extend>>
(UC3)<.up.(UC1) : <<extend>>
(UC2)<.down.(UC6): <<include>>
(UC9)<.up.(UC4) : <<extend>>
(UC10)<.up.(UC4) : <<extend>>

@enduml