@startuml "Cliente use-cases"
left to right direction

actor Cliente as C

package MatchSquad {

    usecase "Cadastrar" as UC1
    usecase "Login/Logout" as UC2
    usecase "Gerenciar Perfil" as UC3
    usecase "Pesquisar Consultor" as UC4
    usecase "Agendar Reunião" as UC5
    usecase "Pagar Consultoria" as UC6
    usecase "Consultar Agendamento" as UC7
    usecase "Cancelar Agendamento" as UC8
    usecase "Realizar Consultoria" as UC9
    usecase "Avaliar Consultaria" as UC10
    usecase "Consultar Relatório de Reunião" as UC11
    usecase "Recuperar senha" as UC12
    'usecase "Trocar Consultor" as UC13'
}

C -up-> UC1
C -up-> UC2
C --> UC3
C --> UC4
C --> UC5
C --> UC7
C -up-> UC9
C --> UC10
C --> UC12



(UC6)<.up.(UC5): <<include>>
(UC8).up.>(UC7): <<extend>>
(UC11).up.>(UC7): <<extend>>

@enduml
