@startuml
actor Admin as A

package MatchSquad {
    usecase "Configurar Troca de Comissão" as UC1
    usecase "Acompanhar Faturamento" as UC2
    usecase "Exportar Dados" as UC3
    usecase "Visualizar Dashboard" as UC4
    usecase "Bloquear Usuário" as UC5
    usecase "Envio de Comunicados" as UC6
    usecase "Login/Logout" as UC7

}

A --> UC1
A --> UC2
A --> UC3
A --> UC4
A --> UC5
A --> UC6
A --> UC7


@enduml