@startuml "Cliente use-cases"
left to right direction
actor Cliente as C

package MatchSquad {

    usecase "Adicionar Cartões de Crédito" as UC1
    usecase "Agendar Reunião" as UC2
    usecase "Pagar Consultoria - API" as UC3
    usecase "Cancelar Agendamento" as UC4
    usecase "Assistir Consultoria" as UC5
    usecase "Consultar Agendamentos" as UC7
    usecase "Pesquisar Consultor" as UC8
    usecase "Consultar Agendamento" as UC9
    usecase "Avaliar Consultaria" as UC9
    usecase "Consultar Relatório de Reunião" as UC9
    usecase "Fazer login" as UC10
    usecase "Fazer logout" as UC11
    usecase "Cadastrar" as UC12
    usecase "Recuperar senha" as UC13

}

C --> UC9
C --> UC1
C --> UC2
C --> UC3
C --> UC5
C --> UC7
C --> UC8
C --> UC10
C --> UC11
C --> UC12
C --> UC13



(UC4).up.>(UC7): <<extend>>


@enduml